apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: firebird-vpa
  namespace: firebird
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: firebird5-1
  updatePolicy:
    updateMode: "Off"    # Pode ser "Off", "Initial", ou "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: firebird
      minAllowed:
        cpu: 800m
        memory: 3Gi
      maxAllowed:
        cpu: 2
        memory: 8Gi
